const KEYS = {
  jobs: "postits_jobs",
  applications: "postits_applications",
  userRoles: "postits_user_roles",
};

const SEED_JOBS = [
  // DMV Area - Washington DC
  {
    id: "seed-1",
    title: "Senior Software Engineer",
    company: "Beltway Tech Solutions",
    location: "Washington, DC",
    salary: "$145,000 – $175,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["React", "Node.js", "AWS"],
    description: "Build scalable web platforms for federal clients. 3 days remote, 2 days on-site. Great benefits and flexible hours.",
    requirements: "5+ years of software engineering experience\nStrong React and Node.js skills\nExperience with AWS services\nExcellent communication skills",
    imageUrl: "",
    employerEmail: "demo@beltwaytech.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-2",
    title: "Policy Analyst",
    company: "Capitol Hill Associates",
    location: "Washington, DC",
    salary: "$75,000 – $95,000",
    commute: "Metro accessible",
    type: "On-site",
    tags: ["Policy Research", "Writing", "Government"],
    description: "Analyze federal legislation and draft policy briefs for senior leadership. Work at the intersection of technology and public policy.",
    requirements: "3+ years of policy analysis experience\nStrong research and writing skills\nKnowledge of federal legislative process\nMaster's degree preferred",
    imageUrl: "",
    employerEmail: "demo@capitolhill.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-3",
    title: "Cybersecurity Analyst",
    company: "FedSecure",
    location: "Washington, DC",
    salary: "$110,000 – $140,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["SIEM", "Threat Intelligence", "Security Clearance"],
    description: "Protect federal agency networks from cyber threats. Work with cutting-edge security tools in a high-impact environment.",
    requirements: "3+ years of cybersecurity experience\nActive security clearance preferred\nCISSP or CEH certification\nExperience with SIEM tools",
    imageUrl: "",
    employerEmail: "demo@fedsecure.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-4",
    title: "UX Designer",
    company: "Capitol Creative Agency",
    location: "Washington, DC",
    salary: "$90,000 – $115,000",
    commute: "Metro accessible",
    type: "On-site",
    tags: ["Figma", "User Research", "Design Systems"],
    description: "Shape digital experiences for policy and advocacy organizations. Work with a passionate creative team in the heart of DC.",
    requirements: "3+ years of UX design experience\nStrong Figma skills\nPortfolio demonstrating user-centered design\nExperience with design systems",
    imageUrl: "",
    employerEmail: "demo@capitolcreative.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-5",
    title: "Communications Director",
    company: "DC Advocacy Group",
    location: "Washington, DC",
    salary: "$95,000 – $120,000",
    commute: "Metro accessible",
    type: "On-site",
    tags: ["PR", "Media Relations", "Strategic Communications"],
    description: "Lead communications strategy for a prominent DC advocacy organization. Manage media relations and public messaging.",
    requirements: "7+ years of communications experience\nEstablished media relationships in DC\nStrong writing and public speaking skills\nCrisis communications experience",
    imageUrl: "",
    employerEmail: "demo@dcadvocacy.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-6",
    title: "Government Affairs Manager",
    company: "National Trade Association",
    location: "Washington, DC",
    salary: "$105,000 – $130,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Lobbying", "Policy", "Stakeholder Relations"],
    description: "Represent association interests before Congress and federal agencies. Build relationships with key policymakers.",
    requirements: "5+ years of government affairs experience\nExisting Hill relationships\nStrong understanding of legislative process\nJD or Master's preferred",
    imageUrl: "",
    employerEmail: "demo@nationaltrade.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-7",
    title: "Data Scientist",
    company: "DC Analytics Lab",
    location: "Washington, DC",
    salary: "$125,000 – $155,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Python", "Machine Learning", "TensorFlow"],
    description: "Apply machine learning to solve complex public sector challenges. Work on impactful projects across health, education, and justice.",
    requirements: "4+ years of data science experience\nPhD or Master's in relevant field\nStrong Python and ML skills\nExperience with large datasets",
    imageUrl: "",
    employerEmail: "demo@dcanalytics.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-8",
    title: "Financial Analyst",
    company: "World Bank Group",
    location: "Washington, DC",
    salary: "$85,000 – $110,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Financial Modeling", "Excel", "International Development"],
    description: "Support financial analysis for international development projects. Work with global teams on high-impact initiatives.",
    requirements: "3+ years of financial analysis experience\nCFA designation preferred\nStrong Excel and financial modeling skills\nInternational development interest",
    imageUrl: "",
    employerEmail: "demo@worldbank.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-9",
    title: "Program Manager",
    company: "USAID Contractor",
    location: "Washington, DC",
    salary: "$100,000 – $125,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Program Management", "International Development", "PMP"],
    description: "Manage international development programs funded by USAID. Coordinate with partners across multiple countries.",
    requirements: "5+ years of program management experience\nPMP certification preferred\nInternational development experience\nFluency in second language a plus",
    imageUrl: "",
    employerEmail: "demo@usaidcontractor.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-10",
    title: "Marketing Manager",
    company: "Dupont Circle Startup",
    location: "Washington, DC",
    salary: "$80,000 – $100,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Digital Marketing", "SEO", "Content Strategy"],
    description: "Drive growth for a fast-growing DC tech startup. Own the full marketing funnel from awareness to conversion.",
    requirements: "4+ years of marketing experience\nStrong digital marketing skills\nExperience with SEO and content strategy\nData-driven mindset",
    imageUrl: "",
    employerEmail: "demo@dupontcircle.com",
    postedAt: new Date().toISOString(),
  },
  // Virginia
  {
    id: "seed-11",
    title: "Cloud Architect",
    company: "AWS Government Services",
    location: "Arlington, VA",
    salary: "$160,000 – $195,000",
    commute: "~10 min from DC",
    type: "Hybrid",
    tags: ["AWS", "Cloud Architecture", "Security Clearance"],
    description: "Design and implement cloud solutions for federal government clients. Lead technical teams on large-scale migrations.",
    requirements: "7+ years of cloud architecture experience\nAWS Solutions Architect certification\nActive TS/SCI clearance preferred\nFederal contracting experience",
    imageUrl: "",
    employerEmail: "demo@awsgov.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-12",
    title: "Intelligence Analyst",
    company: "Defense Contractor",
    location: "Arlington, VA",
    salary: "$95,000 – $125,000",
    commute: "~10 min from DC",
    type: "On-site",
    tags: ["Intelligence Analysis", "Security Clearance", "OSINT"],
    description: "Provide analytical support to Department of Defense clients. Work on national security missions with real impact.",
    requirements: "Active TS/SCI clearance required\n3+ years of intelligence analysis experience\nStrong analytical and writing skills\nMilitary or IC background preferred",
    imageUrl: "",
    employerEmail: "demo@defensecontractor.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-13",
    title: "Product Manager",
    company: "RemoteFirst Inc.",
    location: "Reston, VA",
    salary: "$130,000 – $160,000",
    commute: "~25 min from DC",
    type: "Remote",
    tags: ["Agile", "Roadmapping", "SaaS"],
    description: "Lead a fully distributed team building HR tech SaaS. Own the product roadmap and drive customer outcomes.",
    requirements: "4+ years of product management experience\nExperience with agile methodologies\nStrong stakeholder management skills\nSaaS product experience",
    imageUrl: "",
    employerEmail: "demo@remotefirst.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-14",
    title: "DevOps Engineer",
    company: "CloudGov Partners",
    location: "Reston, VA",
    salary: "$155,000 – $185,000",
    commute: "~25 min from DC",
    type: "Remote",
    tags: ["Kubernetes", "Terraform", "CI/CD"],
    description: "High-compensation role supporting government cloud infrastructure. Mostly remote with occasional travel to DC.",
    requirements: "4+ years of DevOps experience\nStrong Kubernetes and Terraform skills\nExperience with CI/CD pipelines\nSecurity clearance a plus",
    imageUrl: "",
    employerEmail: "demo@cloudgov.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-15",
    title: "Systems Engineer",
    company: "Northrop Grumman",
    location: "Herndon, VA",
    salary: "$120,000 – $150,000",
    commute: "~30 min from DC",
    type: "Hybrid",
    tags: ["Systems Engineering", "DoD", "MBSE"],
    description: "Support complex defense systems engineering programs. Work with cross-functional teams on cutting-edge technology.",
    requirements: "5+ years of systems engineering experience\nActive secret clearance\nMBSE experience preferred\nDefense industry background",
    imageUrl: "",
    employerEmail: "demo@northropgrumman.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-16",
    title: "Software Developer",
    company: "Leidos",
    location: "Chantilly, VA",
    salary: "$110,000 – $140,000",
    commute: "~35 min from DC",
    type: "Hybrid",
    tags: ["Java", "Python", "Agile"],
    description: "Develop software solutions for intelligence community clients. Work on programs with real national security impact.",
    requirements: "3+ years of software development experience\nActive TS/SCI clearance required\nJava or Python proficiency\nAgile development experience",
    imageUrl: "",
    employerEmail: "demo@leidos.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-17",
    title: "HR Business Partner",
    company: "Capital One",
    location: "McLean, VA",
    salary: "$95,000 – $120,000",
    commute: "~20 min from DC",
    type: "Hybrid",
    tags: ["HR", "Talent Management", "Employee Relations"],
    description: "Partner with business leaders to drive people strategy at one of the nation's top financial institutions.",
    requirements: "5+ years of HR business partner experience\nStrong employee relations skills\nExperience with talent management\nPHR or SHRM certification preferred",
    imageUrl: "",
    employerEmail: "demo@capitalone.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-18",
    title: "Network Engineer",
    company: "Booz Allen Hamilton",
    location: "McLean, VA",
    salary: "$115,000 – $145,000",
    commute: "~20 min from DC",
    type: "Hybrid",
    tags: ["Cisco", "Network Security", "CCNP"],
    description: "Design and maintain enterprise networks for federal government clients. Work on mission-critical infrastructure.",
    requirements: "4+ years of network engineering experience\nCCNP certification required\nActive secret clearance\nFederal IT experience preferred",
    imageUrl: "",
    employerEmail: "demo@boozallen.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-19",
    title: "Accountant",
    company: "PwC Federal Practice",
    location: "McLean, VA",
    salary: "$75,000 – $95,000",
    commute: "~20 min from DC",
    type: "Hybrid",
    tags: ["CPA", "Federal Accounting", "Audit"],
    description: "Support federal government audit and accounting engagements. Work with top-tier clients on complex financial challenges.",
    requirements: "2+ years of accounting experience\nCPA license or candidate\nFederal accounting experience preferred\nStrong analytical skills",
    imageUrl: "",
    employerEmail: "demo@pwcfederal.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-20",
    title: "Business Analyst",
    company: "Deloitte Federal",
    location: "Arlington, VA",
    salary: "$85,000 – $110,000",
    commute: "~10 min from DC",
    type: "Hybrid",
    tags: ["Business Analysis", "Process Improvement", "Agile"],
    description: "Support federal agency transformation initiatives. Analyze business processes and drive efficiency improvements.",
    requirements: "3+ years of business analysis experience\nAgile or Scrum certification preferred\nFederal consulting experience a plus\nStrong communication skills",
    imageUrl: "",
    employerEmail: "demo@deloittefederal.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-21",
    title: "Contracts Manager",
    company: "SAIC",
    location: "Fairfax, VA",
    salary: "$100,000 – $130,000",
    commute: "~30 min from DC",
    type: "Hybrid",
    tags: ["Government Contracts", "FAR", "Procurement"],
    description: "Manage complex government contracts and ensure FAR compliance at a leading defense and technology company.",
    requirements: "5+ years of government contracting experience\nStrong FAR/DFARS knowledge\nCPCM certification preferred\nActive secret clearance",
    imageUrl: "",
    employerEmail: "demo@saic.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-22",
    title: "Technical Writer",
    company: "ManTech International",
    location: "Fairfax, VA",
    salary: "$75,000 – $95,000",
    commute: "~30 min from DC",
    type: "Hybrid",
    tags: ["Technical Writing", "Documentation", "Security Clearance"],
    description: "Create clear technical documentation for complex defense and intelligence systems.",
    requirements: "3+ years of technical writing experience\nActive secret clearance preferred\nStrong writing and editing skills\nDefense industry experience",
    imageUrl: "",
    employerEmail: "demo@mantech.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-23",
    title: "Scrum Master",
    company: "ICF International",
    location: "Reston, VA",
    salary: "$95,000 – $120,000",
    commute: "~25 min from DC",
    type: "Hybrid",
    tags: ["Scrum", "Agile", "Jira", "CSM"],
    description: "Facilitate agile delivery for federal consulting engagements. Coach teams and remove impediments to delivery.",
    requirements: "CSM certification required\n4+ years of scrum master experience\nFederal consulting experience preferred\nSAFe certification a plus",
    imageUrl: "",
    employerEmail: "demo@icfinternational.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-24",
    title: "Robotics Engineer",
    company: "DARPA Contractor",
    location: "Arlington, VA",
    salary: "$140,000 – $175,000",
    commute: "~10 min from DC",
    type: "Hybrid",
    tags: ["Robotics", "ROS", "Computer Vision", "C++"],
    description: "Push the boundaries of robotics technology on DARPA-funded research programs. Work on the bleeding edge of autonomous systems.",
    requirements: "PhD in robotics or related field\nStrong ROS and C++ skills\nActive secret clearance preferred\nStrong publication record",
    imageUrl: "",
    employerEmail: "demo@darpacontractor.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-25",
    title: "Machine Learning Engineer",
    company: "In-Q-Tel",
    location: "Arlington, VA",
    salary: "$145,000 – $180,000",
    commute: "~10 min from DC",
    type: "Hybrid",
    tags: ["Machine Learning", "Python", "Computer Vision", "NLP"],
    description: "Apply cutting-edge ML to national security challenges at the CIA's venture capital arm.",
    requirements: "PhD or MS in ML or related field\nActive TS/SCI clearance preferred\nStrong Python and deep learning skills\nNLP or computer vision expertise",
    imageUrl: "",
    employerEmail: "demo@inqtel.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-26",
    title: "Frontend Developer",
    company: "Axios HQ",
    location: "Arlington, VA",
    salary: "$105,000 – $135,000",
    commute: "~10 min from DC",
    type: "Hybrid",
    tags: ["React", "TypeScript", "CSS", "Performance"],
    description: "Build the digital products powering one of DC's most innovative media companies. Work on products read by millions.",
    requirements: "4+ years of frontend development\nStrong React and TypeScript skills\nPerformance optimization experience\nMedia industry interest",
    imageUrl: "",
    employerEmail: "demo@axioshq.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-27",
    title: "Civil Engineer",
    company: "VDOT",
    location: "Richmond, VA",
    salary: "$75,000 – $100,000",
    commute: "Richmond area",
    type: "Hybrid",
    tags: ["Civil Engineering", "Transportation", "AutoCAD Civil 3D"],
    description: "Design and oversee transportation infrastructure projects across Virginia.",
    requirements: "PE license in Virginia\n4+ years of civil engineering experience\nTransportation design experience\nStrong AutoCAD Civil 3D skills",
    imageUrl: "",
    employerEmail: "demo@vdot.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-28",
    title: "Security Operations Analyst",
    company: "Peraton",
    location: "Herndon, VA",
    salary: "$95,000 – $125,000",
    commute: "~30 min from DC",
    type: "Hybrid",
    tags: ["SOC", "Incident Response", "Splunk", "Security Clearance"],
    description: "Monitor and respond to cybersecurity threats for critical government infrastructure in a 24/7 SOC environment.",
    requirements: "Active TS/SCI clearance required\n3+ years of SOC experience\nStrong Splunk skills\nCEH or Security+ certification",
    imageUrl: "",
    employerEmail: "demo@peraton.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-29",
    title: "Geospatial Analyst",
    company: "NGA Contractor",
    location: "Springfield, VA",
    salary: "$100,000 – $130,000",
    commute: "~25 min from DC",
    type: "On-site",
    tags: ["GIS", "Remote Sensing", "GEOINT", "ArcGIS"],
    description: "Analyze geospatial intelligence to support national security missions at the National Geospatial-Intelligence Agency.",
    requirements: "Active TS/SCI clearance required\n4+ years of GEOINT experience\nStrong ArcGIS skills\nRemote sensing experience",
    imageUrl: "",
    employerEmail: "demo@ngacontractor.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-30",
    title: "Cybersecurity Engineer",
    company: "MITRE Corporation",
    location: "McLean, VA",
    salary: "$120,000 – $155,000",
    commute: "~20 min from DC",
    type: "Hybrid",
    tags: ["Cybersecurity", "Vulnerability Research", "MITRE ATT&CK"],
    description: "Advance national cybersecurity at a Federally Funded R&D Center. Work on research that shapes global cyber defense.",
    requirements: "5+ years of cybersecurity experience\nActive TS/SCI clearance preferred\nVulnerability research experience\nStrong reverse engineering skills",
    imageUrl: "",
    employerEmail: "demo@mitre.org",
    postedAt: new Date().toISOString(),
  },
  // Maryland
  {
    id: "seed-31",
    title: "Data Analyst",
    company: "NIH Contractor",
    location: "Bethesda, MD",
    salary: "$85,000 – $105,000",
    commute: "~15 min from DC",
    type: "Hybrid",
    tags: ["Python", "SQL", "Tableau"],
    description: "Support health outcomes research with federal data. Short commute from most of DC with parking available.",
    requirements: "2+ years of data analysis experience\nProficiency in Python and SQL\nExperience with Tableau\nHealthcare experience a plus",
    imageUrl: "",
    employerEmail: "demo@nihcontractor.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-32",
    title: "Biomedical Engineer",
    company: "FDA Division",
    location: "Silver Spring, MD",
    salary: "$90,000 – $115,000",
    commute: "~20 min from DC",
    type: "Hybrid",
    tags: ["Biomedical Engineering", "Regulatory Affairs", "Medical Devices"],
    description: "Review medical device submissions and support regulatory decision-making at the FDA.",
    requirements: "3+ years of biomedical engineering experience\nKnowledge of FDA regulatory process\nMaster's or PhD preferred\nStrong technical writing skills",
    imageUrl: "",
    employerEmail: "demo@fda.gov",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-33",
    title: "Epidemiologist",
    company: "CDC Regional Office",
    location: "Rockville, MD",
    salary: "$85,000 – $110,000",
    commute: "~25 min from DC",
    type: "Hybrid",
    tags: ["Epidemiology", "Public Health", "SAS"],
    description: "Conduct disease surveillance and outbreak investigations in the DC metro area.",
    requirements: "MPH or PhD in epidemiology\n3+ years of epidemiology experience\nStrong SAS or R skills\nField investigation experience",
    imageUrl: "",
    employerEmail: "demo@cdcregional.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-34",
    title: "Aerospace Engineer",
    company: "NASA Goddard",
    location: "Greenbelt, MD",
    salary: "$105,000 – $135,000",
    commute: "~30 min from DC",
    type: "Hybrid",
    tags: ["Aerospace Engineering", "Spacecraft", "MATLAB"],
    description: "Work on next-generation spacecraft systems at NASA Goddard Space Flight Center.",
    requirements: "4+ years of aerospace engineering experience\nMaster's degree preferred\nStrong MATLAB and simulation skills\nUS citizenship required",
    imageUrl: "",
    employerEmail: "demo@nasa.gov",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-35",
    title: "Supply Chain Manager",
    company: "Lockheed Martin",
    location: "Bethesda, MD",
    salary: "$110,000 – $140,000",
    commute: "~15 min from DC",
    type: "Hybrid",
    tags: ["Supply Chain", "Procurement", "Defense"],
    description: "Manage complex defense supply chains for major government programs.",
    requirements: "5+ years of supply chain management experience\nActive secret clearance preferred\nCPSM certification a plus\nDefense industry experience",
    imageUrl: "",
    employerEmail: "demo@lockheedmartin.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-36",
    title: "Environmental Scientist",
    company: "EPA Chesapeake Bay Office",
    location: "Annapolis, MD",
    salary: "$70,000 – $90,000",
    commute: "~45 min from DC",
    type: "Hybrid",
    tags: ["Environmental Science", "Water Quality", "GIS"],
    description: "Monitor and protect the Chesapeake Bay ecosystem. Conduct field research and analyze environmental data.",
    requirements: "3+ years of environmental science experience\nStrong GIS skills\nWater quality monitoring experience\nMS in environmental science preferred",
    imageUrl: "",
    employerEmail: "demo@epachesapeake.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-37",
    title: "Nurse Practitioner",
    company: "Johns Hopkins Medical Center",
    location: "Baltimore, MD",
    salary: "$105,000 – $130,000",
    commute: "~45 min from DC",
    type: "On-site",
    tags: ["Nurse Practitioner", "Primary Care", "EMR"],
    description: "Provide primary care services at one of the world's top medical institutions.",
    requirements: "Active NP license in Maryland\n2+ years of NP experience\nPrimary care experience preferred\nStrong patient communication skills",
    imageUrl: "",
    employerEmail: "demo@hopkinsmedical.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-38",
    title: "Software Engineer",
    company: "Micros Systems",
    location: "Columbia, MD",
    salary: "$100,000 – $130,000",
    commute: "~35 min from DC",
    type: "Hybrid",
    tags: ["Java", "Microservices", "Docker"],
    description: "Build enterprise hospitality software used by thousands of hotels worldwide.",
    requirements: "3+ years of Java development experience\nMicroservices architecture experience\nDocker and Kubernetes knowledge\nStrong problem-solving skills",
    imageUrl: "",
    employerEmail: "demo@microssystems.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-39",
    title: "Logistics Coordinator",
    company: "Port of Baltimore",
    location: "Baltimore, MD",
    salary: "$60,000 – $80,000",
    commute: "~45 min from DC",
    type: "On-site",
    tags: ["Logistics", "Supply Chain", "Operations"],
    description: "Coordinate freight and shipping operations at one of the East Coast's busiest ports.",
    requirements: "2+ years of logistics experience\nStrong organizational skills\nKnowledge of customs and trade regulations\nForklift certification a plus",
    imageUrl: "",
    employerEmail: "demo@portofbaltimore.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-40",
    title: "Teacher — High School Math",
    company: "Montgomery County Public Schools",
    location: "Rockville, MD",
    salary: "$55,000 – $85,000",
    commute: "~25 min from DC",
    type: "On-site",
    tags: ["Teaching", "Mathematics", "Education"],
    description: "Inspire the next generation of mathematicians in one of the nation's top school districts.",
    requirements: "Maryland teaching license\nMath certification required\nStrong classroom management skills\nPassion for student success",
    imageUrl: "",
    employerEmail: "demo@mcps.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-41",
    title: "Occupational Therapist",
    company: "Kennedy Krieger Institute",
    location: "Baltimore, MD",
    salary: "$75,000 – $95,000",
    commute: "~45 min from DC",
    type: "On-site",
    tags: ["Occupational Therapy", "Pediatrics", "Neurodevelopment"],
    description: "Help children with neurodevelopmental disabilities achieve their fullest potential.",
    requirements: "MOT or OTD degree required\nActive Maryland OT license\nPediatric experience preferred\nSensory integration expertise a plus",
    imageUrl: "",
    employerEmail: "demo@kennedykrieger.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-42",
    title: "Mobile Developer — iOS",
    company: "Tegrity Health",
    location: "Baltimore, MD",
    salary: "$115,000 – $145,000",
    commute: "~45 min from DC",
    type: "Hybrid",
    tags: ["Swift", "iOS", "HealthKit"],
    description: "Build health monitoring apps that improve patient outcomes and make a real difference in people's lives.",
    requirements: "4+ years of iOS development\nStrong Swift skills\nHealthKit experience preferred\nHIPAA compliance knowledge",
    imageUrl: "",
    employerEmail: "demo@tegrityhealth.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-43",
    title: "Real Estate Analyst",
    company: "JBG Smith Properties",
    location: "Bethesda, MD",
    salary: "$80,000 – $105,000",
    commute: "~15 min from DC",
    type: "Hybrid",
    tags: ["Real Estate", "Financial Modeling", "Market Analysis"],
    description: "Analyze real estate investment opportunities across the DC metro market.",
    requirements: "2+ years of real estate analysis experience\nStrong financial modeling skills\nDC market knowledge preferred\nExcel and Argus proficiency",
    imageUrl: "",
    employerEmail: "demo@jbgsmith.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-44",
    title: "Biotechnology Sales Rep",
    company: "Thermo Fisher Scientific",
    location: "Gaithersburg, MD",
    salary: "$90,000 – $120,000",
    commute: "~25 min from DC",
    type: "Hybrid",
    tags: ["Sales", "Biotechnology", "Life Sciences"],
    description: "Sell life science research products to leading biotech and pharmaceutical companies in the DC corridor.",
    requirements: "3+ years of life science sales experience\nBiology or chemistry degree preferred\nStrong relationship-building skills\nTrack record of exceeding quota",
    imageUrl: "",
    employerEmail: "demo@thermofisher.com",
    postedAt: new Date().toISOString(),
  },
  // More DC Area
  {
    id: "seed-45",
    title: "Graphic Designer",
    company: "National Geographic Partners",
    location: "Washington, DC",
    salary: "$65,000 – $85,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Graphic Design", "Adobe Creative Suite", "Editorial"],
    description: "Create stunning visual content for one of the world's most iconic media brands.",
    requirements: "3+ years of graphic design experience\nStrong Adobe Creative Suite skills\nEditorial design portfolio\nMotion graphics experience a plus",
    imageUrl: "",
    employerEmail: "demo@natgeo.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-46",
    title: "Lawyer — Government Contracts",
    company: "Wiley Rein LLP",
    location: "Washington, DC",
    salary: "$160,000 – $210,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Government Contracts Law", "Litigation", "FAR"],
    description: "Advise defense contractors and technology companies on complex government contracting legal matters.",
    requirements: "JD from top law school\nActive DC bar license\n3+ years of government contracts law experience\nStrong writing and advocacy skills",
    imageUrl: "",
    employerEmail: "demo@wileyrein.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-47",
    title: "Economist",
    company: "Federal Reserve Board",
    location: "Washington, DC",
    salary: "$110,000 – $145,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Economics", "Monetary Policy", "Research"],
    description: "Conduct economic research to inform Federal Reserve monetary policy alongside world-class economists.",
    requirements: "PhD in economics required\nStrong econometrics skills\nMacroeconomics research experience\nPublication record preferred",
    imageUrl: "",
    employerEmail: "demo@federalreserve.gov",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-48",
    title: "Social Media Manager",
    company: "Georgetown University",
    location: "Washington, DC",
    salary: "$55,000 – $72,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Social Media", "Content Creation", "Higher Education"],
    description: "Manage social media presence for one of America's most prestigious universities.",
    requirements: "2+ years of social media management\nStrong content creation skills\nHigher education experience preferred\nPhotography and video skills a plus",
    imageUrl: "",
    employerEmail: "demo@georgetown.edu",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-49",
    title: "Operations Research Analyst",
    company: "RAND Corporation",
    location: "Washington, DC",
    salary: "$90,000 – $120,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Operations Research", "Modeling", "Defense Policy"],
    description: "Apply analytical methods to solve complex national security and public policy challenges.",
    requirements: "PhD or Master's in operations research\n3+ years of analytical experience\nStrong modeling and simulation skills\nDefense policy interest",
    imageUrl: "",
    employerEmail: "demo@rand.org",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-50",
    title: "Nonprofit Development Director",
    company: "DC Central Kitchen",
    location: "Washington, DC",
    salary: "$85,000 – $110,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Fundraising", "Grant Writing", "Nonprofit Management"],
    description: "Lead fundraising and development strategy for DC's most innovative food justice nonprofit.",
    requirements: "7+ years of nonprofit development experience\nStrong grant writing skills\nMajor gifts experience\nPassion for food justice",
    imageUrl: "",
    employerEmail: "demo@dccentralkitchen.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-51",
    title: "Paralegal",
    company: "Covington & Burling",
    location: "Washington, DC",
    salary: "$55,000 – $75,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Legal Research", "Paralegal", "Litigation Support"],
    description: "Support attorneys on high-profile litigation and regulatory matters at a top DC law firm.",
    requirements: "Paralegal certificate or relevant degree\n2+ years of paralegal experience\nStrong legal research skills\nExperience with Westlaw or LexisNexis",
    imageUrl: "",
    employerEmail: "demo@covingtonburling.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-52",
    title: "Research Librarian",
    company: "Library of Congress",
    location: "Washington, DC",
    salary: "$65,000 – $85,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Library Science", "Research", "Digital Archives"],
    description: "Preserve and provide access to the world's largest library collection.",
    requirements: "MLS from ALA-accredited program\n3+ years of research library experience\nDigital archives experience preferred\nSubject expertise in relevant field",
    imageUrl: "",
    employerEmail: "demo@loc.gov",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-53",
    title: "Procurement Specialist",
    company: "Department of Homeland Security",
    location: "Washington, DC",
    salary: "$75,000 – $95,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Federal Procurement", "FAR", "Contract Administration"],
    description: "Manage procurement activities supporting critical homeland security missions.",
    requirements: "3+ years of federal procurement experience\nDAWIA certification preferred\nStrong FAR knowledge\nActive secret clearance",
    imageUrl: "",
    employerEmail: "demo@dhs.gov",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-54",
    title: "Veterinarian",
    company: "National Zoo",
    location: "Washington, DC",
    salary: "$90,000 – $120,000",
    commute: "Metro accessible",
    type: "On-site",
    tags: ["Veterinary Medicine", "Zoo Medicine", "Wildlife"],
    description: "Provide veterinary care for one of the world's most diverse animal collections at the Smithsonian National Zoo.",
    requirements: "DVM degree required\nActive DC veterinary license\nZoo or wildlife medicine experience\nBoard certification preferred",
    imageUrl: "",
    employerEmail: "demo@nationalzoo.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-55",
    title: "Event Planner",
    company: "Smithsonian Institution",
    location: "Washington, DC",
    salary: "$55,000 – $75,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Event Planning", "Venue Management", "Logistics"],
    description: "Plan and execute world-class events at the Smithsonian's iconic venues across DC.",
    requirements: "3+ years of event planning experience\nCMP certification preferred\nVenue management experience\nBudget management skills",
    imageUrl: "",
    employerEmail: "demo@smithsonian.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-56",
    title: "Physical Therapist",
    company: "MedStar Georgetown",
    location: "Washington, DC",
    salary: "$80,000 – $100,000",
    commute: "Metro accessible",
    type: "On-site",
    tags: ["Physical Therapy", "Orthopedics", "Sports Medicine"],
    description: "Provide physical therapy services to diverse patient populations at a leading academic medical center.",
    requirements: "DPT degree required\nActive DC PT license\nOrthopedic experience preferred\nSports medicine background a plus",
    imageUrl: "",
    employerEmail: "demo@medstargeorgetown.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-57",
    title: "Diversity & Inclusion Manager",
    company: "Fannie Mae",
    location: "Washington, DC",
    salary: "$100,000 – $130,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["DEI", "HR", "Program Management"],
    description: "Lead diversity, equity and inclusion initiatives at one of the nation's largest financial institutions.",
    requirements: "5+ years of DEI program experience\nStrong program management skills\nData-driven approach to DEI\nExcellent facilitation skills",
    imageUrl: "",
    employerEmail: "demo@fanniemae.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-58",
    title: "Structural Engineer",
    company: "HNTB Corporation",
    location: "Washington, DC",
    salary: "$90,000 – $120,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Structural Engineering", "Bridge Design", "SAP2000"],
    description: "Design bridges and transportation structures that will serve DC communities for generations.",
    requirements: "PE license required\n5+ years of structural engineering experience\nBridge design experience\nStrong SAP2000 or STAAD skills",
    imageUrl: "",
    employerEmail: "demo@hntb.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-59",
    title: "Management Consultant",
    company: "McKinsey & Company",
    location: "Washington, DC",
    salary: "$175,000 – $225,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Management Consulting", "Strategy", "Federal"],
    description: "Solve the most complex challenges facing government and nonprofit clients at the world's premier consulting firm.",
    requirements: "MBA from top program\nStrong analytical skills\nFederal sector experience preferred\nExceptional communication abilities",
    imageUrl: "",
    employerEmail: "demo@mckinsey.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-60",
    title: "Photojournalist",
    company: "Washington Post",
    location: "Washington, DC",
    salary: "$65,000 – $90,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Photography", "Journalism", "Visual Storytelling"],
    description: "Capture the defining images of our time for one of America's most important newspapers.",
    requirements: "5+ years of professional photojournalism experience\nStrong portfolio of published work\nBreaking news experience\nVideo skills a plus",
    imageUrl: "",
    employerEmail: "demo@washingtonpost.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-61",
    title: "Treasury Analyst",
    company: "US Department of Treasury",
    location: "Washington, DC",
    salary: "$80,000 – $105,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Treasury", "Financial Analysis", "Federal Finance"],
    description: "Support critical financial operations at the Department of the Treasury with national economic impact.",
    requirements: "3+ years of financial analysis experience\nFederal finance experience preferred\nStrong Excel skills\nCPA or CFA preferred",
    imageUrl: "",
    employerEmail: "demo@treasury.gov",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-62",
    title: "Communications Coordinator",
    company: "Dupont Circle Nonprofit",
    location: "Washington, DC",
    salary: "$55,000 – $68,000",
    commute: "Walkable / Metro",
    type: "On-site",
    tags: ["Content Writing", "Social Media", "Email Marketing"],
    description: "Tell the story of a mission-driven environmental nonprofit right in the heart of DC.",
    requirements: "2+ years of communications experience\nStrong writing and editing skills\nSocial media management experience\nPassion for environmental causes",
    imageUrl: "",
    employerEmail: "demo@dupontnonprofit.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-63",
    title: "Information Security Manager",
    company: "Freddie Mac",
    location: "McLean, VA",
    salary: "$130,000 – $165,000",
    commute: "~20 min from DC",
    type: "Hybrid",
    tags: ["Information Security", "CISSP", "Risk Management"],
    description: "Lead information security programs protecting one of the nation's largest mortgage finance companies.",
    requirements: "CISSP certification required\n7+ years of information security experience\nFinancial services background\nStrong risk management skills",
    imageUrl: "",
    employerEmail: "demo@freddiemac.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-64",
    title: "Legislative Assistant",
    company: "US Senate Office",
    location: "Washington, DC",
    salary: "$50,000 – $65,000",
    commute: "Metro accessible",
    type: "On-site",
    tags: ["Legislative Affairs", "Policy Research", "Capitol Hill"],
    description: "Support a US Senator with legislative research, constituent services, and policy development.",
    requirements: "Bachelor's degree required\nCapitol Hill experience preferred\nStrong research and writing skills\nPassion for public service",
    imageUrl: "",
    employerEmail: "demo@senate.gov",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-65",
    title: "Instructional Designer",
    company: "American University",
    location: "Washington, DC",
    salary: "$65,000 – $85,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Instructional Design", "eLearning", "Canvas", "Articulate"],
    description: "Design engaging online and hybrid learning experiences for one of DC's most innovative universities.",
    requirements: "3+ years of instructional design experience\nStrong Articulate or Captivate skills\nHigher education experience preferred\nLearning theory knowledge",
    imageUrl: "",
    employerEmail: "demo@american.edu",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-66",
    title: "Dentist",
    company: "DC Smiles Group",
    location: "Washington, DC",
    salary: "$150,000 – $200,000",
    commute: "Metro accessible",
    type: "On-site",
    tags: ["Dentistry", "General Dentistry", "Patient Care"],
    description: "Join a growing dental practice serving DC's diverse communities with modern technology and great work-life balance.",
    requirements: "DDS or DMD degree required\nActive DC dental license\n2+ years of general dentistry experience\nStrong patient communication skills",
    imageUrl: "",
    employerEmail: "demo@dcsmilesgroup.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-67",
    title: "Sustainability Manager",
    company: "JLL Washington DC",
    location: "Washington, DC",
    salary: "$90,000 – $115,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Sustainability", "LEED", "ESG", "Green Building"],
    description: "Lead sustainability initiatives for a portfolio of premier commercial real estate assets in the DC market.",
    requirements: "LEED AP certification required\n5+ years of sustainability management experience\nESG reporting experience\nStrong stakeholder management skills",
    imageUrl: "",
    employerEmail: "demo@jlldc.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-68",
    title: "AI Policy Researcher",
    company: "Center for Security and Emerging Technology",
    location: "Washington, DC",
    salary: "$85,000 – $110,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["AI Policy", "Research", "Technology Policy"],
    description: "Research the national security implications of artificial intelligence at Georgetown's premier tech policy think tank.",
    requirements: "Master's or PhD in relevant field\n3+ years of policy research experience\nTechnology policy background\nStrong writing and analytical skills",
    imageUrl: "",
    employerEmail: "demo@cset.georgetown.edu",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-69",
    title: "Clinical Psychologist",
    company: "Walter Reed Medical Center",
    location: "Bethesda, MD",
    salary: "$95,000 – $125,000",
    commute: "~15 min from DC",
    type: "On-site",
    tags: ["Psychology", "PTSD", "Military Mental Health"],
    description: "Provide psychological services to active duty military and veterans at the nation's premier military medical center.",
    requirements: "PhD or PsyD in clinical psychology\nActive Maryland license\nMilitary or VA experience preferred\nPTSD treatment specialization",
    imageUrl: "",
    employerEmail: "demo@walterreed.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-70",
    title: "Architect — Interior Design",
    company: "Gensler DC",
    location: "Washington, DC",
    salary: "$80,000 – $110,000",
    commute: "Metro accessible",
    type: "Hybrid",
    tags: ["Interior Architecture", "Revit", "Workplace Design"],
    description: "Design innovative workplace interiors for leading organizations in the DC metro area.",
    requirements: "5+ years of interior architecture experience\nLicensed architect or NCIDQ certification\nStrong Revit skills\nWorkplace design portfolio",
    imageUrl: "",
    employerEmail: "demo@genslerdc.com",
    postedAt: new Date().toISOString(),
  },
  // Remote
  {
    id: "seed-71",
    title: "Full Stack Developer",
    company: "TechForward Inc.",
    location: "Fully Remote (US)",
    salary: "$120,000 – $150,000",
    commute: "No commute",
    type: "Remote",
    tags: ["React", "Python", "PostgreSQL"],
    description: "Build products used by millions of users. Work fully remote with a tight-knit team that values autonomy and impact.",
    requirements: "4+ years of full stack development\nStrong React and Python skills\nPostgreSQL or similar database experience\nRemote work experience preferred",
    imageUrl: "",
    employerEmail: "demo@techforward.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-72",
    title: "Content Strategist",
    company: "Digital Media Co.",
    location: "Fully Remote (US)",
    salary: "$70,000 – $90,000",
    commute: "No commute",
    type: "Remote",
    tags: ["Content Strategy", "SEO", "Editorial"],
    description: "Shape content strategy for a fast-growing digital media company. Lead editorial direction and drive organic growth.",
    requirements: "4+ years of content strategy experience\nStrong SEO knowledge\nEditorial leadership experience\nExcellent writing skills",
    imageUrl: "",
    employerEmail: "demo@digitalmediaco.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-73",
    title: "Customer Success Manager",
    company: "SaaS Platform Co.",
    location: "Fully Remote (US)",
    salary: "$80,000 – $100,000",
    commute: "No commute",
    type: "Remote",
    tags: ["Customer Success", "SaaS", "Account Management"],
    description: "Help enterprise customers get maximum value from our platform. Build long-term relationships and drive retention.",
    requirements: "3+ years of customer success experience\nSaaS account management background\nStrong communication skills\nExperience with Salesforce or HubSpot",
    imageUrl: "",
    employerEmail: "demo@saasplatform.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-74",
    title: "Data Engineer",
    company: "Remote Data Labs",
    location: "Fully Remote (US)",
    salary: "$130,000 – $160,000",
    commute: "No commute",
    type: "Remote",
    tags: ["Spark", "Airflow", "dbt", "Snowflake"],
    description: "Build and maintain data pipelines that power business intelligence across the organization.",
    requirements: "4+ years of data engineering experience\nStrong Spark and Airflow skills\nSnowflake or BigQuery experience\ndbt proficiency preferred",
    imageUrl: "",
    employerEmail: "demo@remotedatalabs.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-75",
    title: "Technical Recruiter",
    company: "TalentSearch Remote",
    location: "Fully Remote (US)",
    salary: "$70,000 – $95,000",
    commute: "No commute",
    type: "Remote",
    tags: ["Recruiting", "Technical Hiring", "ATS"],
    description: "Source and hire top engineering talent for high-growth tech companies.",
    requirements: "3+ years of technical recruiting experience\nStrong sourcing skills\nExperience with ATS platforms\nAbility to assess technical skills",
    imageUrl: "",
    employerEmail: "demo@talentsearch.com",
    postedAt: new Date().toISOString(),
  },
  // New York
  {
    id: "seed-76",
    title: "Investment Banking Analyst",
    company: "Goldman Sachs",
    location: "New York, NY",
    salary: "$110,000 – $150,000",
    commute: "Subway accessible",
    type: "On-site",
    tags: ["Investment Banking", "Financial Modeling", "M&A"],
    description: "Join one of Wall Street's most prestigious banks. Work on high-profile M&A and capital markets transactions.",
    requirements: "Bachelor's degree in finance or related field\nStrong financial modeling skills\nExcellent analytical abilities\nHigh tolerance for demanding hours",
    imageUrl: "",
    employerEmail: "demo@goldmansachs.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-77",
    title: "UX Research Lead",
    company: "NYC Tech Studio",
    location: "New York, NY",
    salary: "$120,000 – $150,000",
    commute: "Subway accessible",
    type: "Hybrid",
    tags: ["UX Research", "Usability Testing", "Qualitative Research"],
    description: "Lead user research across a portfolio of consumer products. Build the research practice and mentor junior researchers.",
    requirements: "6+ years of UX research experience\nStrong qualitative and quantitative methods\nTeam leadership experience\nPortfolio of research case studies",
    imageUrl: "",
    employerEmail: "demo@nyctechstudio.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-78",
    title: "Fashion Buyer",
    company: "Macy's Corporate",
    location: "New York, NY",
    salary: "$75,000 – $100,000",
    commute: "Subway accessible",
    type: "Hybrid",
    tags: ["Buying", "Merchandising", "Retail"],
    description: "Source and select product assortments for one of America's most iconic department stores.",
    requirements: "3+ years of retail buying experience\nStrong trend forecasting skills\nNegotiation experience\nMerchandising or fashion background",
    imageUrl: "",
    employerEmail: "demo@macyscorporate.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-79",
    title: "Media Planner",
    company: "Publicis Media NYC",
    location: "New York, NY",
    salary: "$65,000 – $85,000",
    commute: "Subway accessible",
    type: "Hybrid",
    tags: ["Media Planning", "Digital Advertising", "Analytics"],
    description: "Plan and execute media campaigns for Fortune 500 clients at one of the world's top advertising agencies.",
    requirements: "2+ years of media planning experience\nStrong analytical skills\nDigital advertising knowledge\nExperience with media planning tools",
    imageUrl: "",
    employerEmail: "demo@publicismedia.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-80",
    title: "Architect",
    company: "Skidmore Owings & Merrill",
    location: "New York, NY",
    salary: "$90,000 – $120,000",
    commute: "Subway accessible",
    type: "Hybrid",
    tags: ["Architecture", "Revit", "Sustainability"],
    description: "Design iconic buildings and urban spaces with a world-renowned architecture firm.",
    requirements: "5+ years of architecture experience\nLicensed architect preferred\nStrong Revit skills\nSustainable design experience",
    imageUrl: "",
    employerEmail: "demo@som.com",
    postedAt: new Date().toISOString(),
  },
  // Boston
  {
    id: "seed-81",
    title: "Biotech Research Scientist",
    company: "Moderna Cambridge",
    location: "Cambridge, MA",
    salary: "$115,000 – $145,000",
    commute: "T accessible",
    type: "On-site",
    tags: ["mRNA", "Molecular Biology", "R&D"],
    description: "Advance cutting-edge mRNA therapeutics at one of biotech's most innovative companies.",
    requirements: "PhD in molecular biology or related field\n3+ years of industry R&D experience\nStrong mRNA or vaccine experience\nPublished research record",
    imageUrl: "",
    employerEmail: "demo@modernacambridge.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-82",
    title: "Software Engineer — AI",
    company: "MIT CSAIL Spinout",
    location: "Boston, MA",
    salary: "$140,000 – $175,000",
    commute: "T accessible",
    type: "Hybrid",
    tags: ["AI", "PyTorch", "NLP", "Python"],
    description: "Build AI-powered products at a cutting-edge MIT spinout. Turn world-class research into real product.",
    requirements: "4+ years of ML engineering experience\nStrong PyTorch skills\nNLP or computer vision background\nPublications or open source contributions a plus",
    imageUrl: "",
    employerEmail: "demo@mitcsail.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-83",
    title: "Financial Planner",
    company: "Fidelity Investments",
    location: "Boston, MA",
    salary: "$80,000 – $105,000",
    commute: "T accessible",
    type: "Hybrid",
    tags: ["Financial Planning", "CFP", "Wealth Management"],
    description: "Help individuals and families achieve their financial goals at one of America's largest investment firms.",
    requirements: "CFP certification required\n3+ years of financial planning experience\nStrong client relationship skills\nSeries 7 and 66 licenses",
    imageUrl: "",
    employerEmail: "demo@fidelity.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-84",
    title: "Healthcare Consultant",
    company: "Boston Consulting Group",
    location: "Boston, MA",
    salary: "$130,000 – $165,000",
    commute: "T accessible",
    type: "Hybrid",
    tags: ["Healthcare Consulting", "Strategy", "Analytics"],
    description: "Advise leading healthcare organizations on strategy, operations, and digital transformation.",
    requirements: "MBA from top program\n3+ years of consulting experience\nHealthcare industry knowledge\nStrong analytical and communication skills",
    imageUrl: "",
    employerEmail: "demo@bcgboston.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-85",
    title: "Marine Biologist",
    company: "Woods Hole Oceanographic",
    location: "Woods Hole, MA",
    salary: "$65,000 – $85,000",
    commute: "Cape Cod area",
    type: "On-site",
    tags: ["Marine Biology", "Field Research", "Oceanography"],
    description: "Conduct groundbreaking research on marine ecosystems at one of the world's premier oceanographic institutions.",
    requirements: "PhD in marine biology or related field\nField research experience\nStrong publication record\nGrant writing experience preferred",
    imageUrl: "",
    employerEmail: "demo@whoi.com",
    postedAt: new Date().toISOString(),
  },
  // Philadelphia
  {
    id: "seed-86",
    title: "Pharmacist",
    company: "Penn Medicine",
    location: "Philadelphia, PA",
    salary: "$120,000 – $145,000",
    commute: "SEPTA accessible",
    type: "On-site",
    tags: ["Pharmacy", "Clinical Pharmacology", "EMR"],
    description: "Provide clinical pharmacy services at one of the nation's leading academic medical centers.",
    requirements: "PharmD required\nActive Pennsylvania pharmacist license\nClinical pharmacy experience\nBoard certification preferred",
    imageUrl: "",
    employerEmail: "demo@pennmedicine.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-87",
    title: "Data Engineer",
    company: "Comcast Technology Solutions",
    location: "Philadelphia, PA",
    salary: "$115,000 – $145,000",
    commute: "SEPTA accessible",
    type: "Hybrid",
    tags: ["Scala", "Kafka", "Spark", "AWS"],
    description: "Build data infrastructure powering one of America's largest media and technology companies.",
    requirements: "4+ years of data engineering experience\nStrong Scala and Spark skills\nKafka streaming experience\nCloud platform expertise",
    imageUrl: "",
    employerEmail: "demo@comcasttech.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-88",
    title: "Urban Planner",
    company: "City of Philadelphia",
    location: "Philadelphia, PA",
    salary: "$65,000 – $85,000",
    commute: "SEPTA accessible",
    type: "Hybrid",
    tags: ["Urban Planning", "GIS", "Zoning"],
    description: "Shape the future of Philadelphia through thoughtful urban planning and community development.",
    requirements: "Master's in urban planning\n3+ years of municipal planning experience\nStrong GIS skills\nCommunity engagement experience",
    imageUrl: "",
    employerEmail: "demo@philaplanning.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-89",
    title: "Social Worker",
    company: "Children's Hospital of Philadelphia",
    location: "Philadelphia, PA",
    salary: "$55,000 – $72,000",
    commute: "SEPTA accessible",
    type: "On-site",
    tags: ["Social Work", "Pediatrics", "Case Management"],
    description: "Support children and families navigating complex medical situations at one of the world's top pediatric hospitals.",
    requirements: "MSW required\nLCSW or LSW license in Pennsylvania\nPediatric social work experience preferred\nStrong crisis intervention skills",
    imageUrl: "",
    employerEmail: "demo@chop.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-90",
    title: "Marketing Analyst",
    company: "Day One Agency Philly",
    location: "Philadelphia, PA",
    salary: "$60,000 – $80,000",
    commute: "SEPTA accessible",
    type: "Hybrid",
    tags: ["Marketing Analytics", "Google Analytics", "Data Visualization"],
    description: "Analyze marketing performance and drive data-driven decisions for a growing creative agency.",
    requirements: "2+ years of marketing analytics experience\nStrong Google Analytics skills\nData visualization proficiency\nExcellent presentation skills",
    imageUrl: "",
    employerEmail: "demo@dayoneagency.com",
    postedAt: new Date().toISOString(),
  },
  // Atlanta
  {
    id: "seed-91",
    title: "Software Engineer — Backend",
    company: "NCR Corporation",
    location: "Atlanta, GA",
    salary: "$110,000 – $140,000",
    commute: "MARTA accessible",
    type: "Hybrid",
    tags: ["Java", "Spring Boot", "Microservices"],
    description: "Build payment and commerce platforms used by retailers worldwide. Work on high-throughput systems.",
    requirements: "4+ years of backend development\nStrong Java and Spring Boot skills\nMicroservices architecture experience\nPayments industry experience a plus",
    imageUrl: "",
    employerEmail: "demo@ncrcorp.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-92",
    title: "Public Health Advisor",
    company: "CDC Headquarters",
    location: "Atlanta, GA",
    salary: "$85,000 – $110,000",
    commute: "MARTA accessible",
    type: "Hybrid",
    tags: ["Public Health", "Epidemiology", "Policy"],
    description: "Shape public health policy at the world's premier public health agency.",
    requirements: "MPH or PhD in public health\n5+ years of public health experience\nStrong policy writing skills\nFederal government experience preferred",
    imageUrl: "",
    employerEmail: "demo@cdc.gov",
    postedAt: new Date().toISOString(),
  },
  // Charlotte
  {
    id: "seed-93",
    title: "Wealth Management Associate",
    company: "Bank of America",
    location: "Charlotte, NC",
    salary: "$75,000 – $100,000",
    commute: "CATS accessible",
    type: "Hybrid",
    tags: ["Wealth Management", "Series 7", "Client Relations"],
    description: "Support high-net-worth clients with investment and financial planning at one of America's largest banks.",
    requirements: "Series 7 and 66 licenses\n2+ years of wealth management experience\nStrong client relationship skills\nCFP preferred",
    imageUrl: "",
    employerEmail: "demo@bankofamerica.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-94",
    title: "Electrical Engineer",
    company: "Duke Energy",
    location: "Charlotte, NC",
    salary: "$95,000 – $125,000",
    commute: "Charlotte area",
    type: "Hybrid",
    tags: ["Electrical Engineering", "Power Systems", "AutoCAD"],
    description: "Design and maintain power distribution systems serving millions of customers across the Carolinas.",
    requirements: "PE license preferred\n4+ years of electrical engineering experience\nPower systems experience\nStrong AutoCAD skills",
    imageUrl: "",
    employerEmail: "demo@dukeenergy.com",
    postedAt: new Date().toISOString(),
  },
  // Miami
  {
    id: "seed-95",
    title: "Hospitality Manager",
    company: "Four Seasons Miami",
    location: "Miami, FL",
    salary: "$80,000 – $105,000",
    commute: "Miami area",
    type: "On-site",
    tags: ["Hospitality", "Hotel Management", "Guest Relations"],
    description: "Lead hospitality operations at one of Miami's most prestigious luxury hotels.",
    requirements: "5+ years of hotel management experience\nStrong leadership skills\nLuxury hospitality background\nMultilingual preferred",
    imageUrl: "",
    employerEmail: "demo@fourseasonsmia.com",
    postedAt: new Date().toISOString(),
  },
  {
    id: "seed-96",
    title: "International Trade Specialist",
    company: "PortMiami Trade Center",
    location: "Miami, FL",
    salary: "$70,000 – $90,000",
    commute: "Miami area",
    type: "Hybrid",
    tags: ["International Trade", "Customs", "Logistics"],
    description: "Facilitate international trade operations at one of the Western Hemisphere's busiest seaports.",
    requirements: "3+ years of international trade experience\nCustoms broker license preferred\nSpanish fluency required\nStrong logistics background",
    imageUrl: "",
    employerEmail: "demo@portmiami.com",
    postedAt: new Date().toISOString(),
  },
  // Connecticut
  {
    id: "seed-97",
    title: "Quantitative Analyst",
    company: "Bridgewater Associates",
    location: "Westport, CT",
    salary: "$150,000 – $200,000",
    commute: "Connecticut area",
    type: "Hybrid",
    tags: ["Quantitative Finance", "Python", "R", "Statistics"],
    description: "Build quantitative models at the world's largest hedge fund. Work with brilliant minds on complex financial problems.",
    requirements: "PhD in math, statistics, or related field\nStrong Python and R skills\nFinancial modeling experience\nExceptional analytical abilities",
    imageUrl: "",
    employerEmail: "demo@bridgewater.com",
    postedAt: new Date().toISOString(),
  },
  // Virginia Wine Country
  {
    id: "seed-98",
    title: "Sommelier",
    company: "Inn at Little Washington",
    location: "Washington, VA",
    salary: "$65,000 – $90,000",
    commute: "~70 min from DC",
    type: "On-site",
    tags: ["Wine", "Hospitality", "Fine Dining"],
    description: "Curate the wine experience at one of America's most celebrated restaurants alongside legendary chef Patrick O'Connell.",
    requirements: "Court of Master Sommeliers certification\n5+ years of fine dining experience\nExtensive wine knowledge\nExceptional guest service skills",
    imageUrl: "",
    employerEmail: "demo@theinnatlittlewashington.com",
    postedAt: new Date().toISOString(),
  },
  // Security Clearance / Contractor
  {
    id: "seed-99",
    title: "Security Clearance Investigator",
    company: "CACI International",
    location: "Chantilly, VA",
    salary: "$70,000 – $90,000",
    commute: "~35 min from DC",
    type: "Hybrid",
    tags: ["Background Investigation", "Security Clearance", "Federal"],
    description: "Conduct background investigations for federal security clearance applicants with flexible scheduling.",
    requirements: "Active federal investigator credential preferred\n2+ years of investigation experience\nUS citizenship required\nStrong interview and writing skills",
    imageUrl: "",
    employerEmail: "demo@caci.com",
    postedAt: new Date().toISOString(),
  },
  // Film / Entertainment
  {
    id: "seed-100",
    title: "Film Production Coordinator",
    company: "Tyler Perry Studios",
    location: "Atlanta, GA",
    salary: "$55,000 – $75,000",
    commute: "Atlanta area",
    type: "On-site",
    tags: ["Film Production", "Coordination", "Entertainment"],
    description: "Coordinate production activities at one of America's largest film studios on major film and TV productions.",
    requirements: "2+ years of film production experience\nStrong organizational skills\nAbility to work long hours on set\nEntertainment industry connections a plus",
    imageUrl: "",
    employerEmail: "demo@tylerperrystudios.com",
    postedAt: new Date().toISOString(),
  },
];

function seedJobsIfEmpty() {
  try {
    const existing = JSON.parse(localStorage.getItem(KEYS.jobs) || "[]");
    const hasSeeds = existing.some(j => j.id && j.id.startsWith("seed-"));
    if (!hasSeeds) {
      const merged = [...SEED_JOBS, ...existing];
      localStorage.setItem(KEYS.jobs, JSON.stringify(merged));
    }
  } catch {
    localStorage.setItem(KEYS.jobs, JSON.stringify(SEED_JOBS));
  }
}

seedJobsIfEmpty();

export const storage = {
  getJobs() {
    try {
      return JSON.parse(localStorage.getItem(KEYS.jobs) || "[]");
    } catch { return []; }
  },
  saveJob(job) {
    const jobs = this.getJobs();
    const existing = jobs.findIndex(j => j.id === job.id);
    if (existing >= 0) jobs[existing] = job;
    else jobs.push(job);
    localStorage.setItem(KEYS.jobs, JSON.stringify(jobs));
  },
  deleteJob(jobId) {
    const jobs = this.getJobs().filter(j => j.id !== jobId);
    localStorage.setItem(KEYS.jobs, JSON.stringify(jobs));
  },
  getApplications(jobId) {
    try {
      const all = JSON.parse(localStorage.getItem(KEYS.applications) || "{}");
      return jobId ? (all[jobId] || []) : all;
    } catch { return jobId ? [] : {}; }
  },
  saveApplication(jobId, application) {
    const all = this.getApplications();
    if (!all[jobId]) all[jobId] = [];
    all[jobId].push(application);
    localStorage.setItem(KEYS.applications, JSON.stringify(all));
  },
  getUserRole(email) {
    try {
      const roles = JSON.parse(localStorage.getItem(KEYS.userRoles) || "{}");
      return roles[email] || null;
    } catch { return null; }
  },
  saveUserRole(email, role) {
    const roles = JSON.parse(localStorage.getItem(KEYS.userRoles) || "{}");
    roles[email] = role;
    localStorage.setItem(KEYS.userRoles, JSON.stringify(roles));
  },
};